import { strToU8, zipSync } from "fflate";
import { renderWindowLua } from "./factorioExport.js";
import {
  FACTORIO_DESIGN_FILE_SCHEMA,
  FACTORIO_DESIGN_FILE_PACKAGE_ENTRY,
  createFactorioDesignFileDownload
} from "./factorioDesignFile.js";
import {
  FACTORIO_PACKAGE_MANIFEST_ENTRY,
  renderFactorioPackageManifestJson
} from "./factorioPackageManifest.js";
import {
  FACTORIO_STYLE_CATALOG_SCHEMA,
  FACTORIO_STYLE_CATALOG_SOURCE
} from "./factorioStyleCatalog.js";

export const FACTORIO_PREVIEW_MOD_NAME = "labtorio_gui_preview";
export const FACTORIO_PREVIEW_MOD_VERSION = "0.1.0";
export const FACTORIO_PREVIEW_MOD_FOLDER = `${FACTORIO_PREVIEW_MOD_NAME}_${FACTORIO_PREVIEW_MOD_VERSION}`;
export const FACTORIO_PREVIEW_MOD_ZIP_FILENAME = `${FACTORIO_PREVIEW_MOD_FOLDER}.zip`;
export const FACTORIO_PREVIEW_MOD_DESIGN_FILENAME = FACTORIO_DESIGN_FILE_PACKAGE_ENTRY;
export const FACTORIO_PREVIEW_MOD_MANIFEST_FILENAME = FACTORIO_PACKAGE_MANIFEST_ENTRY;

const ZIP_MTIME = new Date("2024-01-01T00:00:00Z");
const ZIP_OPTIONS = Object.freeze({ level: 9, mtime: ZIP_MTIME });

function assertExportableModel(model) {
  if (!model?.root) {
    throw new Error("Create a window before exporting a Factorio preview mod.");
  }
}

export function renderFactorioModInfoJson() {
  return `${JSON.stringify(
    {
      name: FACTORIO_PREVIEW_MOD_NAME,
      version: FACTORIO_PREVIEW_MOD_VERSION,
      title: "Labtorio GUI Preview",
      author: "Labtorio",
      factorio_version: "2.0",
      dependencies: ["base"],
      description:
        "Local preview mod generated by Labtorio for comparing browser GUI layouts in Factorio."
    },
    null,
    2
  )}\n`;
}

export function renderFactorioModControlLua() {
  return `-- Generated by Labtorio for local GUI parity testing.
-- Rebuilds the preview GUI for each active player when the mod loads or players join.

local build_gui = require("gui")

local function build_for_player(player)
  if player and player.valid then
    build_gui(player)
  end
end

local function rebuild_all_players()
  for _, player in pairs(game.players) do
    build_for_player(player)
  end
end

script.on_init(rebuild_all_players)
script.on_configuration_changed(rebuild_all_players)

script.on_event(defines.events.on_player_created, function(event)
  build_for_player(game.get_player(event.player_index))
end)

script.on_event(defines.events.on_player_joined_game, function(event)
  build_for_player(game.get_player(event.player_index))
end)
`;
}

export function renderFactorioModFiles(model, { editorState = null } = {}) {
  assertExportableModel(model);

  const files = {
    "info.json": renderFactorioModInfoJson(),
    "control.lua": renderFactorioModControlLua(),
    "gui.lua": renderWindowLua(model)
  };

  if (editorState) {
    files[FACTORIO_PREVIEW_MOD_DESIGN_FILENAME] =
      createFactorioDesignFileDownload(editorState).content;
    files[FACTORIO_PREVIEW_MOD_MANIFEST_FILENAME] = renderFactorioPackageManifestJson({
      designEntry: FACTORIO_PREVIEW_MOD_DESIGN_FILENAME,
      designSchema: FACTORIO_DESIGN_FILE_SCHEMA,
      styleCatalog: {
        schema: FACTORIO_STYLE_CATALOG_SCHEMA,
        source: FACTORIO_STYLE_CATALOG_SOURCE
      }
    });
  }

  return Object.freeze(files);
}

export function createFactorioModZipData(model, options = {}) {
  const files = renderFactorioModFiles(model, options);
  const entries = {};

  for (const [fileName, contents] of Object.entries(files)) {
    entries[`${FACTORIO_PREVIEW_MOD_FOLDER}/${fileName}`] = [
      strToU8(contents),
      ZIP_OPTIONS
    ];
  }

  return zipSync(entries, ZIP_OPTIONS);
}

export function createFactorioModDownload(model, options = {}) {
  return {
    filename: FACTORIO_PREVIEW_MOD_ZIP_FILENAME,
    data: createFactorioModZipData(model, options)
  };
}
